package com.gaas.threeKingdoms;

public enum UserCommand {

    // DismantleBehaviorCommandKey
    CHOOSE_HAND_CARD,
    CHOOSE_EQUIPMENT_CARD_ID,
    DISMANTLE_BEHAVIOR_PLAYER_ID,
    DISMANTLE_BEHAVIOR_TARGET_PLAYER_ID,
    DISMANTLE_BEHAVIOR_USE_DISMANTLE_EFFECT_CARD_ID,
    SNATCH_BEHAVIOR_PLAYER_ID,
    SNATCH_BEHAVIOR_TARGET_PLAYER_ID,
    SNATCH_BEHAVIOR_USE_DISMANTLE_EFFECT_CARD_ID,
    BORROWED_SWORD_PLAYER_ID,
    BORROWED_SWORD_BORROWED_PLAYER_ID,
    BORROWED_SWORD_ATTACK_TARGET_PLAYER_ID
}
